/* File: gempakmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * See http://cens.ioc.ee/projects/f2py2e/
 * Generation date: Wed Mar  5 14:26:23 2014
 * $Revision:$
 * $Date:$
 * Do not edit this file directly unless you know what you are doing!!!
 */
#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *gempak_error;
static PyObject *gempak_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define STRINGMALLOC(str,len)\
  if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
    PyErr_SetString(PyExc_MemoryError, "out of memory");\
    goto capi_fail;\
  } else {\
    (str)[len] = '\0';\
  }

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (((PyArrayObject *)(capi_ ## var ## _tmp))->nd)
#define old_shape(var,dim) (((PyArrayObject *)(capi_ ## var ## _tmp))->dimensions[dim])
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
  PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
  fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
  PyArrayObject *arr = NULL;
  PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
  if (obj == Py_None) {
    if (*len == -1)
      *len = strlen(inistr); /* Will this cause problems? */
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,inistr,*len+1);
    return 1;
  }
  if (PyArray_Check(obj)) {
    if ((arr = (PyArrayObject *)obj) == NULL)
      goto capi_fail;
    if (!ISCONTIGUOUS(arr)) {
      PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
      goto capi_fail;
    }
    if (*len == -1)
      *len = (arr->descr->elsize)*PyArray_SIZE(arr);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,arr->data,*len+1);
    return 1;
  }
  if (PyString_Check(obj)) {
    tmp = obj;
    Py_INCREF(tmp);
  }
#if PY_VERSION_HEX >= 0x03000000
  else if (PyUnicode_Check(obj)) {
    tmp = PyUnicode_AsASCIIString(obj);
  }
  else {
    PyObject *tmp2;
    tmp2 = PyObject_Str(obj);
    if (tmp2) {
      tmp = PyUnicode_AsASCIIString(tmp2);
      Py_DECREF(tmp2);
    }
    else {
      tmp = NULL;
    }
  }
#else
  else {
    tmp = PyObject_Str(obj);
  }
#endif
  if (tmp == NULL) goto capi_fail;
  if (*len == -1)
    *len = PyString_GET_SIZE(tmp);
  STRINGMALLOC(*str,*len);
  STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
  Py_DECREF(tmp);
  return 1;
capi_fail:
  Py_XDECREF(tmp);
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = gempak_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
  PyObject* tmp = NULL;
  if (PyInt_Check(obj)) {
    *v = (int)PyInt_AS_LONG(obj);
    return 1;
  }
  tmp = PyNumber_Int(obj);
  if (tmp) {
    *v = PyInt_AS_LONG(tmp);
    Py_DECREF(tmp);
    return 1;
  }
  if (PyComplex_Check(obj))
    tmp = PyObject_GetAttrString(obj,"real");
  else if (PyString_Check(obj) || PyUnicode_Check(obj))
    /*pass*/;
  else if (PySequence_Check(obj))
    tmp = PySequence_GetItem(obj,0);
  if (tmp) {
    PyErr_Clear();
    if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
    Py_DECREF(tmp);
  }
  {
    PyObject* err = PyErr_Occurred();
    if (err==NULL) err = gempak_error;
    PyErr_SetString(err,errmess);
  }
  return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************* get_max_grids *******************************/
static char doc_f2py_rout_gempak_gemread_get_max_grids[] = "\
Function signature:\n\
  mxgrd = get_max_grids(gemFilename)\n\
Required arguments:\n"
"  gemFilename : input string(len=-1)\n"
"Return objects:\n"
"  mxgrd : int";
/*  */
static PyObject *f2py_rout_gempak_gemread_get_max_grids(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string gemFilename = NULL;
  int slen(gemFilename);
  PyObject *gemFilename_capi = Py_None;
  int mxgrd = 0;
  static char *capi_kwlist[] = {"gemFilename",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:gempak.gemread.get_max_grids",\
    capi_kwlist,&gemFilename_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable mxgrd */
  /* Processing variable gemFilename */
  slen(gemFilename) = -1;
  f2py_success = string_from_pyobj(&gemFilename,&slen(gemFilename),"",gemFilename_capi,"string_from_pyobj failed in converting 1st argument `gemFilename' of gempak.gemread.get_max_grids to C string");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(gemFilename,&mxgrd,slen(gemFilename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",mxgrd);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
    STRINGFREE(gemFilename);
  }  /*if (f2py_success) of gemFilename*/
  /* End of cleaning variable gemFilename */
  /* End of cleaning variable mxgrd */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of get_max_grids ****************************/

/******************************* get_grid_dims *******************************/
static char doc_f2py_rout_gempak_gemread_get_grid_dims[] = "\
Function signature:\n\
  kx,ky = get_grid_dims(gemFilename)\n\
Required arguments:\n"
"  gemFilename : input string(len=-1)\n"
"Return objects:\n"
"  kx : int\n"
"  ky : int";
/*  */
static PyObject *f2py_rout_gempak_gemread_get_grid_dims(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,int*,int*,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string gemFilename = NULL;
  int slen(gemFilename);
  PyObject *gemFilename_capi = Py_None;
  int kx = 0;
  int ky = 0;
  static char *capi_kwlist[] = {"gemFilename",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:gempak.gemread.get_grid_dims",\
    capi_kwlist,&gemFilename_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable gemFilename */
  slen(gemFilename) = -1;
  f2py_success = string_from_pyobj(&gemFilename,&slen(gemFilename),"",gemFilename_capi,"string_from_pyobj failed in converting 1st argument `gemFilename' of gempak.gemread.get_grid_dims to C string");
  if (f2py_success) {
  /* Processing variable ky */
  /* Processing variable kx */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(gemFilename,&kx,&ky,slen(gemFilename));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("ii",kx,ky);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable kx */
  /* End of cleaning variable ky */
    STRINGFREE(gemFilename);
  }  /*if (f2py_success) of gemFilename*/
  /* End of cleaning variable gemFilename */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/**************************** end of get_grid_dims ****************************/

/********************************* read_grid *********************************/
static char doc_f2py_rout_gempak_gemread_read_grid[] = "\
Function signature:\n\
  read_grid(gemFilename,gdattm1,gdattm2,level1,level2,vcord,parmin,grid)\n\
Required arguments:\n"
"  gemFilename : input string(len=-1)\n"
"  gdattm1 : input string(len=-1)\n"
"  gdattm2 : input string(len=-1)\n"
"  level1 : input int\n"
"  level2 : input int\n"
"  vcord : input string(len=-1)\n"
"  parmin : input string(len=-1)\n"
"  grid : in/output rank-2 array('f') with bounds (f2py_grid_d0,f2py_grid_d1)";
/* #declfortranroutine# */
static PyObject *f2py_rout_gempak_gemread_read_grid(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,string,int*,int*,string,string,float*,int*,int*,size_t,size_t,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string gemFilename = NULL;
  int slen(gemFilename);
  PyObject *gemFilename_capi = Py_None;
  string gdattm1 = NULL;
  int slen(gdattm1);
  PyObject *gdattm1_capi = Py_None;
  string gdattm2 = NULL;
  int slen(gdattm2);
  PyObject *gdattm2_capi = Py_None;
  int level1 = 0;
  PyObject *level1_capi = Py_None;
  int level2 = 0;
  PyObject *level2_capi = Py_None;
  string vcord = NULL;
  int slen(vcord);
  PyObject *vcord_capi = Py_None;
  string parmin = NULL;
  int slen(parmin);
  PyObject *parmin_capi = Py_None;
  float *grid = NULL;
  npy_intp grid_Dims[2] = {-1, -1};
  const int grid_Rank = 2;
  PyArrayObject *capi_grid_tmp = NULL;
  int capi_grid_intent = 0;
  PyObject *grid_capi = Py_None;
  int f2py_grid_d0 = 0;
  int f2py_grid_d1 = 0;
  static char *capi_kwlist[] = {"gemFilename","gdattm1","gdattm2","level1","level2","vcord","parmin","grid",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:gempak.gemread.read_grid",\
    capi_kwlist,&gemFilename_capi,&gdattm1_capi,&gdattm2_capi,&level1_capi,&level2_capi,&vcord_capi,&parmin_capi,&grid_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable vcord */
  slen(vcord) = -1;
  f2py_success = string_from_pyobj(&vcord,&slen(vcord),"",vcord_capi,"string_from_pyobj failed in converting 6th argument `vcord' of gempak.gemread.read_grid to C string");
  if (f2py_success) {
  /* Processing variable gdattm2 */
  slen(gdattm2) = -1;
  f2py_success = string_from_pyobj(&gdattm2,&slen(gdattm2),"",gdattm2_capi,"string_from_pyobj failed in converting 3rd argument `gdattm2' of gempak.gemread.read_grid to C string");
  if (f2py_success) {
  /* Processing variable gdattm1 */
  slen(gdattm1) = -1;
  f2py_success = string_from_pyobj(&gdattm1,&slen(gdattm1),"",gdattm1_capi,"string_from_pyobj failed in converting 2nd argument `gdattm1' of gempak.gemread.read_grid to C string");
  if (f2py_success) {
  /* Processing variable level1 */
    f2py_success = int_from_pyobj(&level1,level1_capi,"gempak.gemread.read_grid() 4th argument (level1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable level2 */
    f2py_success = int_from_pyobj(&level2,level2_capi,"gempak.gemread.read_grid() 5th argument (level2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable grid */
  ;
  capi_grid_intent |= F2PY_INTENT_INOUT;
  capi_grid_tmp = array_from_pyobj(NPY_FLOAT,grid_Dims,grid_Rank,capi_grid_intent,grid_capi);
  if (capi_grid_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gempak_error,"failed in converting 8th argument `grid' of gempak.gemread.read_grid to C/Fortran array" );
  } else {
    grid = (float *)(capi_grid_tmp->data);

  /* Processing variable parmin */
  slen(parmin) = -1;
  f2py_success = string_from_pyobj(&parmin,&slen(parmin),"",parmin_capi,"string_from_pyobj failed in converting 7th argument `parmin' of gempak.gemread.read_grid to C string");
  if (f2py_success) {
  /* Processing variable gemFilename */
  slen(gemFilename) = -1;
  f2py_success = string_from_pyobj(&gemFilename,&slen(gemFilename),"",gemFilename_capi,"string_from_pyobj failed in converting 1st argument `gemFilename' of gempak.gemread.read_grid to C string");
  if (f2py_success) {
  /* Processing variable f2py_grid_d0 */
  f2py_grid_d0 = shape(grid, 0);
  /* Processing variable f2py_grid_d1 */
  f2py_grid_d1 = shape(grid, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(gemFilename,gdattm1,gdattm2,&level1,&level2,vcord,parmin,grid,&f2py_grid_d0,&f2py_grid_d1,slen(gemFilename),slen(gdattm1),slen(gdattm2),slen(vcord),slen(parmin));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_grid_d1 */
  /* End of cleaning variable f2py_grid_d0 */
    STRINGFREE(gemFilename);
  }  /*if (f2py_success) of gemFilename*/
  /* End of cleaning variable gemFilename */
    STRINGFREE(parmin);
  }  /*if (f2py_success) of parmin*/
  /* End of cleaning variable parmin */
  if((PyObject *)capi_grid_tmp!=grid_capi) {
    Py_XDECREF(capi_grid_tmp); }
  }  /*if (capi_grid_tmp == NULL) ... else of grid*/
  /* End of cleaning variable grid */
  } /*if (f2py_success) of level2*/
  /* End of cleaning variable level2 */
  } /*if (f2py_success) of level1*/
  /* End of cleaning variable level1 */
    STRINGFREE(gdattm1);
  }  /*if (f2py_success) of gdattm1*/
  /* End of cleaning variable gdattm1 */
    STRINGFREE(gdattm2);
  }  /*if (f2py_success) of gdattm2*/
  /* End of cleaning variable gdattm2 */
    STRINGFREE(vcord);
  }  /*if (f2py_success) of vcord*/
  /* End of cleaning variable vcord */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of read_grid ******************************/

/******************************* create_gemfile *******************************/
static char doc_f2py_rout_gempak_gemread_create_gemfile[] = "\
Function signature:\n\
  status = create_gemfile(newfname,copyfname,mxgrd)\n\
Required arguments:\n"
"  newfname : input string(len=-1)\n"
"  copyfname : input string(len=-1)\n"
"  mxgrd : input int\n"
"Return objects:\n"
"  status : int";
/*  */
static PyObject *f2py_rout_gempak_gemread_create_gemfile(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,int*,int*,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string newfname = NULL;
  int slen(newfname);
  PyObject *newfname_capi = Py_None;
  string copyfname = NULL;
  int slen(copyfname);
  PyObject *copyfname_capi = Py_None;
  int mxgrd = 0;
  PyObject *mxgrd_capi = Py_None;
  int status = 0;
  static char *capi_kwlist[] = {"newfname","copyfname","mxgrd",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO:gempak.gemread.create_gemfile",\
    capi_kwlist,&newfname_capi,&copyfname_capi,&mxgrd_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable status */
  /* Processing variable newfname */
  slen(newfname) = -1;
  f2py_success = string_from_pyobj(&newfname,&slen(newfname),"",newfname_capi,"string_from_pyobj failed in converting 1st argument `newfname' of gempak.gemread.create_gemfile to C string");
  if (f2py_success) {
  /* Processing variable copyfname */
  slen(copyfname) = -1;
  f2py_success = string_from_pyobj(&copyfname,&slen(copyfname),"",copyfname_capi,"string_from_pyobj failed in converting 2nd argument `copyfname' of gempak.gemread.create_gemfile to C string");
  if (f2py_success) {
  /* Processing variable mxgrd */
    f2py_success = int_from_pyobj(&mxgrd,mxgrd_capi,"gempak.gemread.create_gemfile() 3rd argument (mxgrd) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(newfname,copyfname,&mxgrd,&status,slen(newfname),slen(copyfname));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",status);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of mxgrd*/
  /* End of cleaning variable mxgrd */
    STRINGFREE(copyfname);
  }  /*if (f2py_success) of copyfname*/
  /* End of cleaning variable copyfname */
    STRINGFREE(newfname);
  }  /*if (f2py_success) of newfname*/
  /* End of cleaning variable newfname */
  /* End of cleaning variable status */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/*************************** end of create_gemfile ***************************/

/********************************* write_grid *********************************/
static char doc_f2py_rout_gempak_gemread_write_grid[] = "\
Function signature:\n\
  status = write_grid(gemFilename,gdattm1,gdattm2,level1,level2,vcord,parmin,grid)\n\
Required arguments:\n"
"  gemFilename : input string(len=-1)\n"
"  gdattm1 : input string(len=-1)\n"
"  gdattm2 : input string(len=-1)\n"
"  level1 : input int\n"
"  level2 : input int\n"
"  vcord : input string(len=-1)\n"
"  parmin : input string(len=-1)\n"
"  grid : input rank-2 array('f') with bounds (f2py_grid_d0,f2py_grid_d1)\n"
"Return objects:\n"
"  status : int";
/* #declfortranroutine# */
static PyObject *f2py_rout_gempak_gemread_write_grid(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(string,string,string,int*,int*,string,string,float*,int*,int*,int*,size_t,size_t,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  string gemFilename = NULL;
  int slen(gemFilename);
  PyObject *gemFilename_capi = Py_None;
  string gdattm1 = NULL;
  int slen(gdattm1);
  PyObject *gdattm1_capi = Py_None;
  string gdattm2 = NULL;
  int slen(gdattm2);
  PyObject *gdattm2_capi = Py_None;
  int level1 = 0;
  PyObject *level1_capi = Py_None;
  int level2 = 0;
  PyObject *level2_capi = Py_None;
  string vcord = NULL;
  int slen(vcord);
  PyObject *vcord_capi = Py_None;
  string parmin = NULL;
  int slen(parmin);
  PyObject *parmin_capi = Py_None;
  float *grid = NULL;
  npy_intp grid_Dims[2] = {-1, -1};
  const int grid_Rank = 2;
  PyArrayObject *capi_grid_tmp = NULL;
  int capi_grid_intent = 0;
  PyObject *grid_capi = Py_None;
  int status = 0;
  int f2py_grid_d0 = 0;
  int f2py_grid_d1 = 0;
  static char *capi_kwlist[] = {"gemFilename","gdattm1","gdattm2","level1","level2","vcord","parmin","grid",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOO:gempak.gemread.write_grid",\
    capi_kwlist,&gemFilename_capi,&gdattm1_capi,&gdattm2_capi,&level1_capi,&level2_capi,&vcord_capi,&parmin_capi,&grid_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable status */
  /* Processing variable vcord */
  slen(vcord) = -1;
  f2py_success = string_from_pyobj(&vcord,&slen(vcord),"",vcord_capi,"string_from_pyobj failed in converting 6th argument `vcord' of gempak.gemread.write_grid to C string");
  if (f2py_success) {
  /* Processing variable gdattm2 */
  slen(gdattm2) = -1;
  f2py_success = string_from_pyobj(&gdattm2,&slen(gdattm2),"",gdattm2_capi,"string_from_pyobj failed in converting 3rd argument `gdattm2' of gempak.gemread.write_grid to C string");
  if (f2py_success) {
  /* Processing variable gdattm1 */
  slen(gdattm1) = -1;
  f2py_success = string_from_pyobj(&gdattm1,&slen(gdattm1),"",gdattm1_capi,"string_from_pyobj failed in converting 2nd argument `gdattm1' of gempak.gemread.write_grid to C string");
  if (f2py_success) {
  /* Processing variable level1 */
    f2py_success = int_from_pyobj(&level1,level1_capi,"gempak.gemread.write_grid() 4th argument (level1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable level2 */
    f2py_success = int_from_pyobj(&level2,level2_capi,"gempak.gemread.write_grid() 5th argument (level2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable grid */
  ;
  capi_grid_intent |= F2PY_INTENT_IN;
  capi_grid_tmp = array_from_pyobj(NPY_FLOAT,grid_Dims,grid_Rank,capi_grid_intent,grid_capi);
  if (capi_grid_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(gempak_error,"failed in converting 8th argument `grid' of gempak.gemread.write_grid to C/Fortran array" );
  } else {
    grid = (float *)(capi_grid_tmp->data);

  /* Processing variable parmin */
  slen(parmin) = -1;
  f2py_success = string_from_pyobj(&parmin,&slen(parmin),"",parmin_capi,"string_from_pyobj failed in converting 7th argument `parmin' of gempak.gemread.write_grid to C string");
  if (f2py_success) {
  /* Processing variable gemFilename */
  slen(gemFilename) = -1;
  f2py_success = string_from_pyobj(&gemFilename,&slen(gemFilename),"",gemFilename_capi,"string_from_pyobj failed in converting 1st argument `gemFilename' of gempak.gemread.write_grid to C string");
  if (f2py_success) {
  /* Processing variable f2py_grid_d0 */
  f2py_grid_d0 = shape(grid, 0);
  /* Processing variable f2py_grid_d1 */
  f2py_grid_d1 = shape(grid, 1);
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
  (*f2py_func)(gemFilename,gdattm1,gdattm2,&level1,&level2,vcord,parmin,grid,&status,&f2py_grid_d0,&f2py_grid_d1,slen(gemFilename),slen(gdattm1),slen(gdattm2),slen(vcord),slen(parmin));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",status);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable f2py_grid_d1 */
  /* End of cleaning variable f2py_grid_d0 */
    STRINGFREE(gemFilename);
  }  /*if (f2py_success) of gemFilename*/
  /* End of cleaning variable gemFilename */
    STRINGFREE(parmin);
  }  /*if (f2py_success) of parmin*/
  /* End of cleaning variable parmin */
  if((PyObject *)capi_grid_tmp!=grid_capi) {
    Py_XDECREF(capi_grid_tmp); }
  }  /*if (capi_grid_tmp == NULL) ... else of grid*/
  /* End of cleaning variable grid */
  } /*if (f2py_success) of level2*/
  /* End of cleaning variable level2 */
  } /*if (f2py_success) of level1*/
  /* End of cleaning variable level1 */
    STRINGFREE(gdattm1);
  }  /*if (f2py_success) of gdattm1*/
  /* End of cleaning variable gdattm1 */
    STRINGFREE(gdattm2);
  }  /*if (f2py_success) of gdattm2*/
  /* End of cleaning variable gdattm2 */
    STRINGFREE(vcord);
  }  /*if (f2py_success) of vcord*/
  /* End of cleaning variable vcord */
  /* End of cleaning variable status */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of write_grid *****************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/

static FortranDataDef f2py_gemread_def[] = {
  {"get_max_grids",-1,{{-1}},0,NULL,(void *)f2py_rout_gempak_gemread_get_max_grids,doc_f2py_rout_gempak_gemread_get_max_grids},
  {"get_grid_dims",-1,{{-1}},0,NULL,(void *)f2py_rout_gempak_gemread_get_grid_dims,doc_f2py_rout_gempak_gemread_get_grid_dims},
  {"read_grid",-1,{{-1}},0,NULL,(void *)f2py_rout_gempak_gemread_read_grid,doc_f2py_rout_gempak_gemread_read_grid},
  {"create_gemfile",-1,{{-1}},0,NULL,(void *)f2py_rout_gempak_gemread_create_gemfile,doc_f2py_rout_gempak_gemread_create_gemfile},
  {"write_grid",-1,{{-1}},0,NULL,(void *)f2py_rout_gempak_gemread_write_grid,doc_f2py_rout_gempak_gemread_write_grid},
  {NULL}
};

static void f2py_setup_gemread(char *get_max_grids,char *get_grid_dims,char *read_grid,char *create_gemfile,char *write_grid) {
  int i_f2py=0;
  f2py_gemread_def[i_f2py++].data = get_max_grids;
  f2py_gemread_def[i_f2py++].data = get_grid_dims;
  f2py_gemread_def[i_f2py++].data = read_grid;
  f2py_gemread_def[i_f2py++].data = create_gemfile;
  f2py_gemread_def[i_f2py++].data = write_grid;
}
extern void F_FUNC(f2pyinitgemread,F2PYINITGEMREAD)(void (*)(char *,char *,char *,char *,char *));
static void f2py_init_gemread(void) {
  F_FUNC(f2pyinitgemread,F2PYINITGEMREAD)(f2py_setup_gemread);
}

/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "gempak",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyObject *PyInit_gempak(void) {
#else
#define RETVAL
PyMODINIT_FUNC initgempak(void) {
#endif
  int i;
  PyObject *m,*d, *s;
#if PY_VERSION_HEX >= 0x03000000
  m = gempak_module = PyModule_Create(&moduledef);
#else
  m = gempak_module = Py_InitModule("gempak", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module gempak (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'gempak' is auto-generated with f2py (version:2).\nFunctions:\n"
"Fortran 90/95 modules:\n""  gemread --- get_max_grids(),get_grid_dims(),read_grid(),create_gemfile(),write_grid()"".");
  PyDict_SetItemString(d, "__doc__", s);
  gempak_error = PyErr_NewException ("gempak.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++)
    PyDict_SetItemString(d, f2py_routine_defs[i].name,PyFortranObject_NewAsAttr(&f2py_routine_defs[i]));





/*eof initf2pywraphooks*/
  PyDict_SetItemString(d, "gemread", PyFortranObject_New(f2py_gemread_def,f2py_init_gemread));
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"gempak");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
